export const products = [
    {
      id: 1,
      title: "Calabrese Broccoli",
      image: "broccoli",
      priceOld: 25,
      priceNew: 21,
      rating: 5,
      category: "Vegetable",
    },
    {
      id: 2,
      title: "Fresh Corn",
      image: "fresh-corn",
      priceOld: 21,
      priceNew: 18,
      rating: 5,
      category: "Vegetable",
    },
    {
      id: 3,
      title: "Dried Pistachio",
      image: "dried-pistachio",
      priceOld: 61,
      priceNew: 48,
      rating: 5,
      category: "Mill",
    },
    {
      id: 4,
      title: "Vegan Red Tomato",
      image: "vegan-red-tomato",
      priceOld: 14,
      priceNew: 9,
      rating: 5,
      category: "Vegetable",
    },
    {
      id: 5,
      title: "Organic Almonds",
      image: "organic-almonds",
      priceOld: 21,
      priceNew: 18,
      rating: 5,
      category: "Fru",
    },
    {
      id: 6,
      title: "Brown Hazelnut",
      image: "brown-hazelnut",
      priceOld: 43,
      priceNew: 34,
      rating: 5,
      category: "Mill",
    },
  ];